import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },

  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },

  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },

  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },

  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },

  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4"
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },

  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
  {
    img: "https://officemart.co.ke/media/cache/5c/f2/5cf22cc2ae38478e88b816d31e4dd7a7.jpg",
    title: "Mathematics",
    star: <AiFillStar className="rating-star" />,
    sold: "(>500 copies)",
    prevPrice: "sh440.00",
    newPrice: "400",
    company: "Spotlight",
    category: "Textbooks",
    ageGroup: "Grade 4",
  },
];

export default data;